### ISSUE TITLE
Don't override SSL_CERT_FILE environment variable

### ISSUE THREAD

**Issue by nerdrew** [google/signet#52]
https://github.com/google/signet/blob/master/lib/signet/ssl_config.rb sets the SSL_CERT_FILE variable. Seems bad.

**Comment by amalagaura** [comment]
Probably related but on JRuby I am getting:

```OpenSSL::X509::StoreError: setting default path failed: problem creating X509 Aux certificate: java.io.IOException: problem parsing cert: java.security.cert.CertificateParsingException: java.io.IOException: Duplicate extensions not allowed```

JRuby has already loaded the certs but signet is also trying to do it. I don't have this problem with other libraries which do OAuth.

**Comment by amalagaura** [comment]
On a fresh Jruby 1.7.19 install I can only get Signet working if I remove the ssl_config.rb file. It looks like a hack which was maybe needed a few years ago.

**Comment by creddy** [comment]
:+1:

**Comment by sqrrrl** [comment]
Removed in next version :)
