### ISSUE TITLE
I would like to see more examples about use of signet

### ISSUE THREAD

**Issue by jylitalo** [google/signet#59]
My current attempt on accessing Google always ends up with invalid_grant.

Here is the problematic part of the code:
oauth2_client = Signet::OAuth2::Client.new(authentication_uri: "https://accounts.google.com/o/oauth2/auth",
token_credential_uri: "https://accounts.google.com/o/oauth2/token",
client_id: "XXXXXXXXXXX-lotOfGibberish.apps.googleusercontent.com",
client_secret: "clientSecretFromGoogleConsole",
redirect_uri: "urn:ietf:wg:oauth:2.0:oob",
scope: "https://picasaweb.google.com/data/",
refresh_token: "inventedStringHere")
p oauth2_client.refresh!

And end result is always:
gems/ruby-2.1.1/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:947:in `fetch_access_token': Authorization failed.  Server message: (Signet::AuthorizationError)
{
  "error" : "invalid_grant"
}

Many OAuth2 errors seem to be related to clock, but that shouldn't be the problem:
$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
*defra1-ntp-002. .GPSs.           1 u    2   64  377   41.766   31.970   8.969

**Comment by gambaroff** [comment]
Is it for an installed application or for a server to server application?

**Comment by jylitalo** [comment]
I have small ruby script that gets executed from command line, so I guess it falls into installed apps category. Script goes through number of files and local directory tree and determine, which images should be sent in through Picasa API. 
Based on my struggles with signet (and Google OAuth2 on that matter), I think the most confusing part of gist was that it doesn't tell you what steps you have to go through to get valid refresh_token.
I think that is going to be my next challenge, since you can't use refresh token from OAuth2 playground.

**Comment by jylitalo** [comment]
So at the end it went something like this ... 
oauth2_client = Signet::OAuth2::Client.new(
       authorization_uri: "https://accounts.google.com/o/oauth2/auth",
       token_credential_uri: "https://accounts.google.com/o/oauth2/token",
       client_id: client_id,
       client_secret: client_secret,
       redirect_uri: redirect_uri,
       scope: "https://picasaweb.google.com/data/",
       expiry: 3600
)
# you probably don't need all those parameters, but ...
p oauth2_client.authorization_uri.to_s
# visit to the given URL with browser, go through authentication to fetch the code
oauth2_client.code=code_from_browser
oauth2_client.refresh!
# store the refresh_token into some configuration file etc., so that you can use the original gist in a future.

**Comment by gambaroff** [comment]
Sounds like you should go server-to-server route. I would not worry about the refresh token.
require 'google/api_client'
require 'yaml'
opts = YAML.load_file("your-credentials.yml")
service_account_email = opts['service_account_email']
key_file = opts['key_file']
key_secret = opts['key_secret']
@profileID = opts['profileID'].to_s


@client = Google::APIClient.new(
    :application_name => opts['application_name'],
    :application_version => opts['application_version'],
)
key = Google::APIClient::KeyUtils.load_from_pkcs12(key_file, key_secret)

@client.authorization =  Signet::OAuth2::Client.new(
    :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
    :audience => 'https://accounts.google.com/o/oauth2/token',
    :scope => 'https://www.googleapis.com/auth/analytics.readonly',
    :issuer => service_account_email,
    :signing_key => key)
@client

@client.authorization.fetch_access_token!
puts @client.authorization.fetch_access_token!

@analytics ||= @client.discovered_api
