### ISSUE TITLE
access_token always expires in 3600

### ISSUE THREAD

**Issue by artmees** [google/signet#66]
given that I have a `refresh_token` I was able to issue a new `access_token`

```rb
client = Signet::OAuth2::Client.new(
  token_credential_uri: TOKEN_CRED_URI,
  client_id: ENV['GOOGLE_APP_ID'],
  client_secret: ENV['GOOGLE_APP_SECRET'],
  refresh_token: @refresh_token,
  expires_in: 3600 * 24 # extend the validity to 24 hours
).refresh! ['access_token']
```

the problem is that no matter the `expiry`, `expires_in` params I pass... I always get an `access_token`
that is only valid for 3600 seconds

I've also tried
```rb
client.update!(
  expiry: 180,
  access_token: @access_token,
  refresh_token: @refresh_token
).access_token
```

both return an access token that only valid for 3600 seconds 
(verified at https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=ACESS_TOKEN )

**Comment by artmees** [comment]
Going through the developer documentation https://developers.google.com/identity/protocols/OAuth2ServiceAccount
In the required claims it's explicitly stated that

>`exp`	The expiration time of the assertion, specified as seconds since 00:00:00 UTC, January 1, 1970. *This value has a maximum of 1 hour after the issued time.*

it's also mentioned one more time in the "Handling the response" section (towards the end)
> Access tokens expire in one hour and can be reused until they expire.

so I think this conclude that this is not an issue... it's the default (only) behaviour

**Comment by Maulik0923** [comment]
How can i change expiry_in parameter??

**Comment by mad-raz** [comment]
AFAIK, (and according to the documentation at that time) you cannot change the `expires_in` parameter (or at least use a value that is larger than `1.hour.from_now`

**Comment by Maulik0923** [comment]
Thanks for give replay.But if any alternate solution for call google API call without authentication.

**Comment by hauvn99** [comment]
I have same problem with mad-raz. How can i change expiry_in parameter? 
Anybody help?
