### ISSUE TITLE
Use case vs standard oauth2 gem

### ISSUE THREAD

**Issue by phallguy** [google/signet#90]
I apologize if this is covered elsewhere already but couldn't really find what I'm looking for. I'm doing some up-front research for a project trying to decide which dependencies to take on. The [oauth2](https://rubygems.org/gems/oauth2) gem from intridea has ben around for quite some time and is used by several other ruby projects when working with OAuth 2 APIs. 

Why would a project use signet instead of the standard oauth2 gem?

**Comment by dazuma** [comment]
@phallguy That's a good question that I don't have an answer to. Looking at the history on rubygems, it seems this gem and oauth2 were developed about the same time in 2010, so it may have been just a case of parallel development. All the Google API clients use signet. But I'm too new on the project to speak to any functionality/support differences. @sporkmonger Can you shed any more light on this?
